### DISCUSSION TITLE
Control box plugin

### DISCUSSION THREAD

**Discussion by linonetwo** [tiddly-gittly/tiddlywiki-plugins#31] [Ideas]
http://gsd5.tiddlyspot.com/ 有这个开关表单的功能，我感觉很好，我本来还想自己做呢，没想到可以直接接手改造就好了。搞个表单工具箱的开关按钮插件，作为主插件。然后用户可以自己选择要安装哪些表单项自插件，控制自己感兴趣的字段

![](https://user-images.githubusercontent.com/3746270/146404378-42075503-83ef-4248-8fa9-3e280ebfce08.png)

关闭后：

![](https://user-images.githubusercontent.com/3746270/146404456-498ac627-a5f5-46d9-9a90-73b47ae363cb.png)

---

Update：

Use https://github.com/tiddly-gittly/super-tag/

**Comment by linonetwo** [comment]
给加了 `$:/tags/Ontology` 标签的条目上使用 `properties.xxx` 来定义 `xxx` 字段。（参考了 JSONSchema 的定义）

字段的值是本体名，GUI 插件会到相应的 `$:/plugins/ontology/XXX` 插件里去找相关定义。

例如

```yaml
title: Todo
tags: $:/tags/Ontology
properties.dueDate: tmo

Some readme content about this tag.
```

会去找 `$:/plugins/ontology/tmo` 里的定义，会去尝试读取 `$:/plugins/ontology/tmo/dueDate` 里的定义。

而 `$:/plugins/ontology/tmo/dueDate` 的内容是一个根据 RDF 写出来的 JSONSchema 片段，类型为 JSON，而且加上 $:/tags/Ontology/Field 让它的内容也可以通过 JSONSchemaForm 来编辑和展示：

```yaml
title: $:/plugins/ontology/tmo/dueDate
tags: $:/tags/Ontology/Field

{
  "type": "string",
  "format": "tw-date-time"
}
```

插件会根据一个条目上的带有 `$:/tags/Ontology` 的标签，拉取其所有以 `properties.` 开头的字段，到对应本体里取 JSONSchema 碎片，拼凑成完整 JSONSchema 后提交给 `https://rjsf-team.github.io/react-jsonschema-form/` 执行。

在实际条目中使用字段时是不带上本体名的，不过如果有冲突现象，为防止两个标签里同名字段冲突，GUI 上会显示一个切换下拉框，让你选择确切的定义。

其实 `$:/tags/Ontology` 类似于 [ShEx](https://github.com/topics/shex)，是利用真正完整的本体里的碎片字段，定义了一个拼凑出来的新的表单本体。

**Comment by linonetwo** [comment]
English version:

Use `properties.xxx` to define the `xxx` field on entries tagged with `$:/tags/Ontology`.

The value of the field is the ontology's name, and the GUI plugin will go to the appropriate `$:/plugins/Ontology/XXX` plugin to find the relevant definition.

For example

```yaml
title: Todo
tags: $:/tags/Ontology
properties.dueDate: tmo

Some readme content about this tag. we use task model ontology's dueDate property.
```

it will look for the definition in `$:/plugins/ontology/tmo` and will try to read the definition in `$:/plugins/ontology/tmo/dueDate`.

The content of `$:/plugins/ontology/tmo/dueDate` is a JSONSchema fragment written from RDF, of type JSON, and the addition of $:/tags/Ontology/Field makes its content editable and presentable via JSONSchemaForm: ```yaml

```yaml
title: $:/plugins/ontology/tmo/dueDate
tags: $:/tags/Ontology/Field

{
  "type": "string",
  "format": "tw-date-time"
}
```

The plugin will pull all fields starting with `properties.` from an entry with tags `$:/tags/Ontology`, fetch the JSONSchema pieces from the corresponding ontology, piece together the complete JSONSchema and submit it to `https://rjsf-team.github.io/ react-jsonschema-form/` for execution.

The fields are used in the actual entry without the ontology name, but if there is a conflict, the GUI will display a toggle dropdown box to let you choose the exact definition in order to prevent the same name field from conflicting in both tags.

In fact, `$:/tags/Ontology` is similar to [ShEx](https://github.com/topics/shex) in that it defines a cobbled-together new form ontology using fragment fields from the real full ontology.

Translated with www.DeepL.com/Translator (free version)
